package org.jd.infestusfrontier.processing.menu;

public enum BowlRefusal {
    NONE,
    STALE_REVISION,
    WRONG_OWNER,
    REMOTE_TARGET,
    TARGET_UNLOADED,
    OUT_OF_REACH,
    MALFORMED_SLOT,
    RATE_LIMITED,
    SERVER_BUSY,
    ACTIVE_BATCH,
    UNKNOWN_RECIPE,
    INSUFFICIENT_ITEM,
    INSUFFICIENT_FLUID,
    OUTPUT_FULL,
    RETURNED_CONTAINER_FULL,
    CARRIED_STACK,
    EMPTY_SLOT,
    IDLE,
    REVISION_EXHAUSTED,
    IDENTIFIER_EXHAUSTED
}
